spring:
  application:
    name: wfs-getway-zuul
server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    #不显示主机名称
    instance-id: wfs-getway-zuul
    #有ip地址显示
    prefer-ip-address: true
zuul:
  routes:
    city:
      path: /city/**
      serviceId: wfs-city-data-api
    data:
      path: /data/**
      serviceId: wfs-weather-data-api